### PR TITLE
Re-render with `conda-smithy` version `1.0.0`

### PR DESCRIPTION
**Pull request by jakirkham**
This is a re-rendering generated with `conda-smithy` version `1.0.0`.

It provides a fix so that the Travis CI and CircleCI builds will be skipped in this feedstock as this is Windows only currently. If this changes, update the `skip` conditions in the recipe and re-render.

Also it starts using [`conda-forge-build-setup`](https://github.com/conda-forge/conda-forge-build-setup-feedstock) to handle standard CI setup like what version of `conda-build` is used. This should allow us to more quickly get out in front of build issues that generally affect feedstocks.

Letting you know @pelson that I'm taking this for a spin.

### CODE REVIEW

**Comment by jankatins** [comment]
LGTM

**Comment by jakirkham** [comment]
The AppVeyor failure already occurs on `master` and has been added to this issue ( https://github.com/conda-forge/miktex-feedstock/issues/10 ).

**Comment by jankatins** [comment]
The failure should be fixed in my update PR, so I'm merging this in and then rebase my PR on top of this

**Comment by jakirkham** [comment]
SGTM

**Pull request merged**
